/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GroupsIndexRouteImport } from './routes/groups/index'
import { Route as GroupsGroupIdIndexRouteImport } from './routes/groups/$groupId/index'
import { Route as GroupsGroupIdEventsEventIdIndexRouteImport } from './routes/groups/$groupId/events/$eventId/index'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIndexRoute = GroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdIndexRoute = GroupsGroupIdIndexRouteImport.update({
  id: '/groups/$groupId/',
  path: '/groups/$groupId/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdEventsEventIdIndexRoute =
  GroupsGroupIdEventsEventIdIndexRouteImport.update({
    id: '/groups/$groupId/events/$eventId/',
    path: '/groups/$groupId/events/$eventId/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/groups': typeof GroupsIndexRoute
  '/groups/$groupId': typeof GroupsGroupIdIndexRoute
  '/groups/$groupId/events/$eventId': typeof GroupsGroupIdEventsEventIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/groups': typeof GroupsIndexRoute
  '/groups/$groupId': typeof GroupsGroupIdIndexRoute
  '/groups/$groupId/events/$eventId': typeof GroupsGroupIdEventsEventIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/groups/': typeof GroupsIndexRoute
  '/groups/$groupId/': typeof GroupsGroupIdIndexRoute
  '/groups/$groupId/events/$eventId/': typeof GroupsGroupIdEventsEventIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/groups'
    | '/groups/$groupId'
    | '/groups/$groupId/events/$eventId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/groups'
    | '/groups/$groupId'
    | '/groups/$groupId/events/$eventId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/groups/'
    | '/groups/$groupId/'
    | '/groups/$groupId/events/$eventId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  GroupsIndexRoute: typeof GroupsIndexRoute
  GroupsGroupIdIndexRoute: typeof GroupsGroupIdIndexRoute
  GroupsGroupIdEventsEventIdIndexRoute: typeof GroupsGroupIdEventsEventIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/': {
      id: '/groups/'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId/': {
      id: '/groups/$groupId/'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof GroupsGroupIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId/events/$eventId/': {
      id: '/groups/$groupId/events/$eventId/'
      path: '/groups/$groupId/events/$eventId'
      fullPath: '/groups/$groupId/events/$eventId'
      preLoaderRoute: typeof GroupsGroupIdEventsEventIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  GroupsIndexRoute: GroupsIndexRoute,
  GroupsGroupIdIndexRoute: GroupsGroupIdIndexRoute,
  GroupsGroupIdEventsEventIdIndexRoute: GroupsGroupIdEventsEventIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
